"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_page from './dashboard-page.bones.json'
import _followups_page from './followups-page.bones.json'
import _todos_page from './todos-page.bones.json'

configureBoneyard({"color":"#f3f4f6","darkColor":"#1f2937","animate":"shimmer","shimmerColor":"#e5e7eb","darkShimmerColor":"#374151","speed":"2s"})

registerBones({
  "dashboard-page": _dashboard_page,
  "followups-page": _followups_page,
  "todos-page": _todos_page,
})
